import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/shared/ui/toaster';
import Providers, { ClientProviders } from '@/config/providers';
import { ReactNode } from 'react';
import { Header } from '@/widgets/Header';
import { AuthModal } from '@/features/auth/ui/AuthModal';
import { setContext } from '@/shared/lib/axios/instance';
import { cookies, headers } from 'next/headers';
import { ErrorBoundary } from '@/shared/lib/errorhandling/ErrorBoundary';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
const breakpoints = {
    mobile: 'xs',
    tablet: 'md',
    desktop: 'lg',
};
export default function ItHubRootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    setContext({ cookie: cookies() });
    const userAgent = headers().get('user-agent') || '';
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <ClientProviders userAgent={userAgent}>
                        <Header />
                        <ErrorBoundary>
                            <AuthModal />
                            {children}
                        </ErrorBoundary>
                    </ClientProviders>
                </Providers>
                <Toaster />
            </body>
        </html>
    );
}
