import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/shared/ui/toaster';
import Providers from '@/config/providers';
import { ReactNode } from 'react';
import { Header } from '@/widgets/Header';
import { RegisterModal } from '@/features/auth/ui/RegisterModal';
import { syncCookies } from '@/shared/lib/cookie/syncCookie';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
const breakpoints = {
    mobile: 'xs',
    tablet: 'md',
    desktop: 'lg',
};
export default function ItHubRootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    syncCookies('server', 'token');
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <RegisterModal />
                    {children}
                </Providers>
                <Toaster />
            </body>
        </html>
    );
}
